#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
FROM ivonet/payara:5.2022.2-jdk17
#FROM ivonet/payara:5.2022.2-jdk11
#FROM payara/server-full:5.2022.2-jdk11
COPY ./artifact/${artifactId}.war $DEPLOY_DIR
